name: Merge Develop into Stage

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '30 6 * * 3'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pull-request-number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automate merging develop into stage'
          branch: develop  # This is the source branch
          base: stage  # This is the target branch
          title: 'Merge Develop into Stage'
          body: 'Automated pull request to merge changes from develop into stage.'
          labels: 'automerge'

  auto-merge:
    needs: create-pull-request
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=${{ needs.create-pull-request.outputs.pr_number }}
          if [ -z "$pr_number" ] || [ "$pr_number" == "null" ]; then
            echo "No pull request was created or found."
            exit 0  # Exit gracefully without an error
          else
            gh pr review $pr_number --approve
            gh pr merge $pr_number --merge --body 'Automated merge completed'
