name: Merge Develop into Stage

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '30 6 * * 3'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Create Pull Request
        run: |
          BASE_BRANCH="stage"
          HEAD_BRANCH="develop"
          PR_TITLE="Merge $HEAD_BRANCH into $BASE_BRANCH"
          PR_BODY="This is an automated pull request to merge changes from $HEAD_BRANCH into $BASE_BRANCH."
          PR_LABEL="automerge"

          gh pr create --base "$BASE_BRANCH" --head "$HEAD_BRANCH" --title "$PR_TITLE" --body "$PR_BODY" --label "$PR_LABEL"

      - name: Debug PR Creation
        run: |
          echo "Pull Request created."

  merge-pull-request:
    runs-on: ubuntu-latest
    needs: create-pull-request
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Get Pull Request Number
        id: get-pull-request
        run: |
          PR_NUMBER=$(gh pr list --base stage --head develop --state open --json number --jq '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Merge Pull Request
        run: |
          PR_NUMBER=${{ env.PR_NUMBER }}
          if [ -z "$PR_NUMBER" ]; then
            echo "No open pull request found."
            exit 1
          fi
          gh pr merge "$PR_NUMBER" --merge --body "Automated merge of develop into stage [skip ci]"