name: Merge Develop into Stage

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '30 6 * * 3'  # Example: At 6:30 AM UTC every Wednesday
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pr_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automate merging develop into stage'
          branch: 'develop'
          base: 'stage'
          title: 'Merge Develop into Stage'
          body: 'Automated pull request to merge changes from develop into stage.'
          labels: 'automerge'

  auto-merge:
    needs: create-pull-request
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=${{ needs.create-pull-request.outputs.pr_number }}
          gh pr review --repo ${{ github.repository }} --approve --pull-request $pr_number
          gh pr merge --repo ${{ github.repository }} --pull-request $pr_number --merge --body 'Automated merge completed'
