name: Merge Develop into Stage

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '30 6 * * 3'  # Runs at 06:30 UTC every Wednesday
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Create Pull Request
        id: create-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          PR_URL=$(gh pr create --base stage --head develop --title "Merge develop into stage" --body "This is an automated pull request to merge changes from develop into stage.")
          echo "Pull Request URL: $PR_URL"

  merge-pull-request:
    runs-on: ubuntu-latest
    needs: create-pull-request
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Get Pull Request Number
        id: get-pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          PULL_REQUEST_NUMBER=$(gh pr list --state open --base stage --head develop --json number --jq '.[0].number')
          if [ -z "$PULL_REQUEST_NUMBER" ]; then
            echo "No open pull request found."
            exit 1
          fi
          echo "::set-output name=pull_number::$PULL_REQUEST_NUMBER"

      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          PULL_REQUEST_NUMBER=${{ steps.get-pull-request.outputs.pull_number }}
          gh pr merge $PULL_REQUEST_NUMBER --merge --delete-branch --subject "Automated merge of develop into stage [skip ci]"