name: Merge Develop into Stage

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '30 6 * * 3'
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: |
          git config --global user.email "${GIT_USER_EMAIL}"
          git config --global user.name "${GIT_USER_NAME}"

      - name: Create Pull Request
        if: github.event_name == 'push'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge develop into stage [skip ci]'
          base: stage
          head: develop
          title: 'Merge develop into stage'
          body: 'This is an automated pull request to merge changes from develop into stage.'
          labels: 'automerge'

  merge-pull-request:
    runs-on: ubuntu-latest
    needs: create-pull-request

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: |
          git config --global user.email "${GIT_USER_EMAIL}"
          git config --global user.name "${GIT_USER_NAME}"

      - name: Merge Pull Request
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: octokit/request-action@v2
        with:
          route: POST /repos/:repository_owner/:repository_name/pulls/:pull_number/merge
          repository_owner: ${{ github.repository_owner }}
          repository_name: ${{ github.event.repository.name }}
          pull_number: ${{ steps.get-pull-request.outputs.pull_number }}
          merge_method: merge
          commit_title: 'Automated merge of develop into stage [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Pull Request Number
        id: get-pull-request
        uses: octokit/request-action@v2
        with:
          route: GET /repos/:repository_owner/:repository_name/pulls
          repository_owner: ${{ github.repository_owner }}
          repository_name: ${{ github.event.repository.name }}
          head: develop
          state: open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
